### ISSUE TITLE
How to have one piece of state depend on another?

### ISSUE THREAD

**Issue by jkseppan** [uriyyo/fastapi-lifespan-manager#141]
Say I want to have one piece of state that is an httpx client and another that is an OpenAI API client, which takes an httpx client on initialization. If I do

```py
manager = LifespanManager()

@manager.add
async def set_up_httpx(app: FastAPI) -> AsyncIterator[State]:
    async with httpx.AsyncClient() as client:
        yield {"http": client}

@manager.add
async def set_up_openapi(app: FastAPI) -> AsyncIterator[State]:
    http: httpx.AsyncClient = app.state.http
    client = AsyncOpenAI(http_client=http)
    yield {"openai": client}
```

the latter call does not receive the state from the earlier call because the state is not attached to the app here: https://github.com/uriyyo/fastapi-lifespan-manager/blob/808e65df3cfdce0fbe200fd8e48383669535a626/fastapi_lifespan_manager/lifespan_manager.py#L98 

Is there a recommended way to do this?

**Comment by uriyyo** [comment]
Hi @jkseppan,

I have just released a new version `0.1.4` that allows access to intermediate state inside lifespan:
```py
manager = LifespanManager()

@manager.add
async def set_up_httpx(app: FastAPI) -> AsyncIterator[State]:
    async with httpx.AsyncClient() as client:
        yield {"http": client}

@manager.add
async def set_up_openapi(app: FastAPI, state: State) -> AsyncIterator[State]:
    http: httpx.AsyncClient = state["http"]
    client = AsyncOpenAI(http_client=http)
    yield {"openai": client}
```

Please, let me know if you have any issues/questions.

**Comment by jkseppan** [comment]
Works nicely, thank you very much!

**Comment by uriyyo** [comment]
Great, can I close this issue?
